# Generated by Django 6.0.5 on 2026-05-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_manager', '0002_moment_is_active_moment_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
